version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pierrenedelec-ng-doc_server_1
      APP_PORT: 80

  server:
    image: ghcr.io/pierrenedelec/ng-doc-pro:latest@sha256:4cbd34918f3be7f9ee63911c5884a40ba56356f0f1eae78f9351090c99c822d1
    restart: on-failure
    init: true
