version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pierrenedelec-ng-doc_server_1
      APP_PORT: 80

  server:
    image: ghcr.io/pierrenedelec/ng-doc-pro:latest@sha256:sha256:10f43fd465c15357dbf289f66ee86940cc9b0e72199b075ebe2df3048aa43077
    restart: on-failure
    init: true
